# Generated by Django 3.1.3 on 2021-03-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('uname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=200)),
                ('psw', models.CharField(max_length=200)),
                ('psw2', models.CharField(max_length=200)),
            ],
        ),
    ]
